---
- hosts: localhost
  gather_facts: no
  tasks:
    - name: Setup python-pip
      raw: apt update && apt install -y python-pip

- hosts: localhost
  roles:
    - build_nginx.role

- hosts: local-nginx
  roles:
    - setup_nginx.role
