- name: Install nginx in docker
  apt: 
    name: nginx
    update_cache: yes

- name: Copy index page
  template:
    src: index.html.j2
    dest: /var/www/html/index.nginx-debian.html

- name: Run nginx
  shell: nginx
